### ISSUE TITLE
Some examples on the "how spelling works" page don't work

### ISSUE THREAD

**Issue by antistic** [morinted/art_of_chording#69]
https://www.artofchording.com/introduction/how-steno-works.html

 e.g. OGS ocean, PHOGS motion, PWA/RA/KU/TKA barracuda, KOFRT comfort

**Comment by morinted** [comment]
How Steno Works uses simple outlines to illustrate points -- it's not meant
to be a literal lesson.

Adding E and * to produce valid outlines may only confuse newcomers.

I may add a footnote pointing this out since you're not the first to
mention it.

As for barracuda and comfort, I'll suggest adding those to the Plover
dictionary.
